<?php
    return [
        'is_parent_category' => 0,
        'not_admin' => true,
        'is_admin' => false,
        'not_ban' => false,
        'not_discount' => 0,
        'five_stars' => 5,
        'publish' => true,
        'payment_method_is_ready' => true,
        'waiting_for_process' => 0,
        'delivering' => 1,
        'done' => 2,
        'cancel' => 3,
        'paginate' => 10,
        'is_male' => 1,
        'is_female' => 0,
        'no_product_sold' => 0,
        'perPage' => 5,
        'get_top_product_discount' => 10,
        'folder_thumbnails' => 'public/thumbnails',
        'thumbnails_path' => 'public/thumbnails/',
        'get_top_new_product' => 3,
        'get_top_seller_product' => 3,
        'cod' => 1,
        'ebank' => 2,
    ];
?>
